name: Generate and push jvm-runtime base image to Dockerhub

on: 
  workflow_dispatch:
    inputs:
      sem-ver:
        type: choice
        description: Version bump 
        required: false
        default: None
        options: 
          - Existing
          - patch
          - minor
          - major
          - None
      replace_prev:
        description: Version bump (Use only for updating existing version)
        required: false
        type: string
        default: ""
      

jobs:
  build-jre-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.BAL_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.BAL_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Generate new tag
        run: |
          username=${{ secrets.BAL_DOCKER_HUB_USERNAME }}
          do_change_latest=1
          do_change_major=1
          do_change_major_minor=1
          formatted_tags=()
          last_tags=()
          i=1
          while :
          do
              retrieved_tags=( $(curl -s -S 'https://hub.docker.com/v2/repositories/'$username'/jvm-runtime/tags/?page='$i'&page_size=100' | jq '."results"[]["name"]') )
              last_tags=( ${last_tags[@]} ${retrieved_tags[@]} )
              if [ ${#retrieved_tags[@]} -lt 100 ] ; then
                  break
              fi
              i=$(($i +1))    
          done

          if [ -z "$last_tags" ]; then
            last_tag="0.0.0"
          else
            IFS=$'\n' sorted_last_tags=($(sort <<<"${last_tags[*]}")); unset IFS  
            last_tag=${sorted_last_tags[-2]}

            for tag_i in ${sorted_last_tags[@]}; do
              if [ $(($(echo "$tag_i" | awk -F. '{ print NF - 1 }') == 2)) -eq 1 ]; then
                formatted_tags=( ${formatted_tags[@]} $tag_i )
              fi
            done
          fi

          last_tag_array=( $(grep -Eo '[0-9]+' <<<"$last_tag") ) 
          major=${last_tag_array[0]}
          minor=${last_tag_array[1]}
          patch=${last_tag_array[2]}
          
          if [ "${{ inputs.replace_prev }}" != "" ] && [ ${{ inputs.sem-ver }} = "Existing" ]; then
            curr_tag=${{ inputs.replace_prev }}
            curr_tag_array=( $(grep -Eo '[0-9]+' <<<"$curr_tag") ) 
            major=${curr_tag_array[0]}
            minor=${curr_tag_array[1]}
            patch=${curr_tag_array[2]}

            for (( i=1; i<${#formatted_tags[@]}; i++ ))
            do 
              prev_tag=${formatted_tags[$i-1]}
              prev_tag_array=( $(grep -Eo '[0-9]+' <<<"$prev_tag") ) 
              prev_major=${prev_tag_array[0]}
              prev_minor=${prev_tag_array[1]}
              prev_patch=${prev_tag_array[2]}

              next_tag=${formatted_tags[$i]}
              next_tag_array=( $(grep -Eo '[0-9]+' <<<"$next_tag") ) 
              next_major=${next_tag_array[0]}
              next_minor=${next_tag_array[1]}
              next_patch=${next_tag_array[2]}

              if [ $major -eq $prev_major ] && [ $minor -eq $prev_minor ] && 
                 [ $patch -eq $prev_patch ] && [ $major -eq $next_major ] && 
                 [ $minor -eq $next_minor ] && [ $patch -eq $(($next_patch - 1)) ] ; then
                    do_change_latest=0
                    do_change_major=0
                    do_change_major_minor=0
    
              elif [ $major -eq $prev_major ] && [ $minor -eq $prev_minor ] && 
                   [ $(("$patch" >= "$prev_patch")) = 1 ] && [ $major -le $next_major ] && 
                   [ $minor -lt $next_minor ]; then
                      do_change_latest=0
                      do_change_major=0
                      do_change_major_minor=1

              elif [ $major -eq $prev_major ] && [ $minor -ge $prev_minor ] && 
                   [ $next_major -gt $major ] ; then
                      do_change_latest=0
                      do_change_major=1
                      do_change_major_minor=1
              fi
            done
          fi
          
          if [ -z ${{ inputs.replace_prev }} ] && [ ${{ inputs.sem-ver }} != "None" ]; then
            if [ ${{ inputs.sem-ver }} = "patch" ] ; then
              patch=$(($patch + 1))
            fi
            if [ ${{ inputs.sem-ver }} = "minor" ] ; then
              minor=$(($minor + 1))
              patch=0
            fi
            if [ ${{ inputs.sem-ver }} = "major" ] ; then
              major=$(($major + 1))
              minor=0
              patch=0
            fi
          fi
          if [ -z ${{ inputs.replace_prev }} ] && [ ${{ inputs.sem-ver }} = "None" ]; then
            echo "Inputs are not given properly"
            exit 1
          fi
          tag="$major.$minor.$patch"
          maj_min_tag="$major.$minor"
          maj_tag="$major"

          generate_only_one_tag=$(($do_change_latest==0 && $do_change_major==0 && $do_change_major_minor==0))
          generate_only_two_tag=$(($do_change_latest==0 && $do_change_major==0 && $do_change_major_minor==1))
          generate_only_three_tag=$(($do_change_latest==0 && $do_change_major==1 && $do_change_major_minor==1))
          generate_only_four_tag=$(($do_change_latest==1 && $do_change_major==1 && $do_change_major_minor==1))

          echo ::set-output name=TAG::$tag
          echo ::set-output name=MAJ_MIN_TAG::$maj_min_tag
          echo ::set-output name=MAJ_TAG::$maj_tag

          echo ::set-output name=GENERATE_ONLY_ONE_TAG::$generate_only_one_tag
          echo ::set-output name=GENERATE_ONLY_TWO_TAG::$generate_only_two_tag
          echo ::set-output name=GENERATE_ONLY_THREE_TAG::$generate_only_three_tag
          echo ::set-output name=GENERATE_ONLY_FOUR_TAG::$generate_only_four_tag
        id: tag-gen
        
      - name: Build and push only major.minor.patch tag
        if: ${{ steps.tag-gen.outputs.GENERATE_ONLY_ONE_TAG == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.TAG }}

      - name: Build and push latest only major.minor.patch, major.minor
        if: ${{ steps.tag-gen.outputs.GENERATE_ONLY_TWO_TAG == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: >
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.TAG }} , 
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.MAJ_MIN_TAG }}

      - name: Build and push latest only major.minor.patch, major.minor, major
        if: ${{ steps.tag-gen.outputs.GENERATE_ONLY_THREE_TAG == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: >
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.TAG }} , 
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.MAJ_MIN_TAG }} , 
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.MAJ_TAG}}

      - name: Build and push latest only major.minor.patch, major.minor, major, latest
        if: ${{ steps.tag-gen.outputs.GENERATE_ONLY_FOUR_TAG == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: > 
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.TAG }}, 
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.MAJ_MIN_TAG }}, 
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:${{ steps.tag-gen.outputs.MAJ_TAG}}, 
            ${{ secrets.BAL_DOCKER_HUB_USERNAME }}/jvm-runtime:latest
