name: Generate and push jvm-runtime base image to Dockerhub

on: 
  workflow_dispatch:
    inputs:
      replace_prev:
        description: Replace previous tag
        required: false
        type: string
        default: ""
      sem-ver:
        type: choice
        description: sem-ver option to increase
        required: false
        options: 
          - patch
          - minor
          - major

jobs:
  build-jre-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Generate new tag
        run: |
          do_change_all=1
          last_tag=( $(curl -s -S 'https://registry.hub.docker.com/v2/repositories/luheerathan/ballerina-jvm-runtime/tags/' | jq '."results"[]["name"]') ) 
          if [ $last_tag != null ]; then
            IFS=$'\n' sorted_last_tag=($(sort <<<"${last_tag[*]}")); unset IFS  
            last_tag=${sorted_last_tag[-2]}
          elif [ $last_tag == null ]; then
            last_tag="0.0.0"
          fi
          if [ ${{ inputs.replace_prev }} != "$last_tag" ] && [ ${{ inputs.replace_prev }} != "" ]; then
            do_change_all=0
          fi
          echo "Last tag is $last_tag"
          echo "Update all tag is $do_all_change"
          
          last_tag_array=( $(grep -Eo '[0-9]+' <<<"$last_tag") ) 

          major=${last_tag_array[0]}
          minor=${last_tag_array[1]}
          patch=${last_tag_array[2]}
          echo $major
          echo $minor
          echo $patch
          
          if [ -z ${{ inputs.replace_prev }} ] ; then
            if [ ${{ inputs.sem-ver }} = "patch" ] ; then
              patch=$(($patch + 1))
            fi
            if [ ${{ inputs.sem-ver }} = "minor" ] ; then
              minor=$(($minor + 1))
              patch=0
            fi
            if [ ${{ inputs.sem-ver }} = "major" ] ; then
              major=$(($major + 1))
              minor=0
              patch=0
            fi
            tag="$major.$minor.$patch"
            maj_min_tag="$major.$minor"
            maj_tag="$major"
          else
            tag=${{ inputs.replace_prev }}
          fi
          echo ::set-output name=TAG::$tag
          echo ::set-output name=MAJ_MIN_TAG::$maj_min_tag
          echo ::set-output name=MAJ_TAG::$maj_tag
          echo ::set-output name=DO_CHANGE_ALL::$do_change_all
          echo $tag
        id: tag-gen
        
      - name: Build and push latest image
        if: ${{ steps.tag-gen.outputs.DO_CHANGE_ALL == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ballerina-jvm-runtime:latest

      - name: Build and push latest major
        if: ${{ steps.tag-gen.outputs.DO_CHANGE_ALL == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ballerina-jvm-runtime:${{ steps.tag-gen.outputs.MAJ_TAG}}

      - name: Build and push latest major.minor
        if: ${{ steps.tag-gen.outputs.DO_CHANGE_ALL == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ballerina-jvm-runtime:${{ steps.tag-gen.outputs.MAJ_MIN_TAG }}

      - name: Build and push latest major.minor.patch
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-image/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ballerina-jvm-runtime:${{ steps.tag-gen.outputs.TAG }}





